name: FGO Login System

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main
  schedule:
    - cron: '30 10 * * *'
    - cron: '01 15 * * *'
    - cron: '01 16 * * *'
    - cron: '01 18 * * *'
    - cron: '01 19 * * *'
    - cron: '01 03 * * *'
    - cron: '01 04 * * *'
    - cron: '01 06 * * *'
    - cron: '01 07 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checking requirements
        run: pip install "https://raw.githubusercontent.com/xdeadboy666x/FGODLBJP/main/requirements.txt" --upgrade
      
      - name: Fetching repository
        uses: actions/checkout@v4

      - name: Execute script 1
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Execute script 2
        run: |
          python3 main02.py
        env:
          userIds: ${{ secrets.GAME_USERIDS }}
          authKeys: ${{ secrets.GAME_AUTHKEYS }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
